### ISSUE TITLE
TypeError: cannot pickle '_thread.RLock' object

### ISSUE THREAD

**Issue by iliailmer** [dylanpeifer/deepgroebner#1] opened 2020-10-12 23:05 UTC
Hi Dylan,

I am trying to run the example experiment from the README.md file:
```
python run.py --variables 3 --degree 20 --generators 10 \
                  --degree_distribution weighted \
                  --value_model degree --value_updates 0
```
 and I encounter an error:
```
Traceback (most recent call last):
  File "run.py", line 348, in <module>
    agent.train(env, episodes=args.episodes, epochs=args.epochs,
  File "/Users/.../deepgroebner/deepgroebner/pg.py", line 360, in train
    return_history = self.run_episodes(
  File "/Users/.../deepgroebner/deepgroebner/pg.py", line 510, in run_episodes
    p.start()
  File "/Users/.../.pyenv/versions/3.8.5/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/.../.pyenv/versions/3.8.5/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/.../.pyenv/versions/3.8.5/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/.../.pyenv/versions/3.8.5/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/.../.pyenv/versions/3.8.5/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/.../.pyenv/versions/3.8.5/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Users/.../.pyenv/versions/3.8.5/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle '_thread.RLock' object
```

do you know what could be the issue? I have TF 2.3.1, running on MacOS 10.15.7

Thank you!

**Comment by dylanpeifer** [comment] 2020-10-12 23:27
I think the problem is something with multiprocessing, which is being used by default to parallelize rollouts across several processes. You should be able to run the example with the additional flag `--parallel False`, though it will be slower depending on how many cores you had available.

I've seen this problem before on a different machine, but I was never able to track it down. Could you send me the output of `conda list` from inside the environment you are running?

**Comment by iliailmer** [comment] 2020-10-16 19:48
I actually used `pyenv` for my environment, so here is the output of `pip list`
```
Package                Version
---------------------- ---------
absl-py                0.10.0
appdirs                1.4.4
appnope                0.1.0
argon2-cffi            20.1.0
astunparse             1.6.3
attrs                  20.1.0
backcall               0.2.0
Beaker                 1.8.1
black                  20.8b1
bleach                 3.1.5
blis                   0.4.1
boto                   2.49.0
boto3                  1.14.48
botocore               1.17.48
cachetools             4.1.1
catalogue              1.0.0
catboost               0.24.1
certifi                2020.6.20
cffi                   1.14.2
chardet                3.0.4
click                  7.1.2
cloudpickle            1.6.0
cycler                 0.10.0
cymem                  2.0.3
Cython                 0.29.21
deap                   1.3.1
decorator              4.4.2
defusedxml             0.6.0
dill                   0.2.9
docutils               0.15.2
entrypoints            0.3
flake8                 3.8.3
Flask                  1.1.2
future                 0.18.2
gast                   0.3.3
gensim                 3.8.3
google-auth            1.22.1
google-auth-oauthlib   0.4.1
google-pasta           0.2.0
graphviz               0.14.1
grpcio                 1.32.0
gym                    0.17.3
h5py                   2.10.0
hmmlearn               0.2.4
idna                   2.10
iniconfig              1.0.1
ipykernel              5.3.4
ipython                7.17.0
ipython-genutils       0.2.0
ipywidgets             7.5.1
itsdangerous           1.1.0
jedi                   0.17.2
Jinja2                 2.11.2
jmespath               0.10.0
joblib                 0.16.0
json5                  0.9.5
jsonschema             3.2.0
jupyter                1.0.0
jupyter-client         6.1.6
jupyter-console        6.1.0
jupyter-core           4.6.3
jupyterlab             2.2.6
jupyterlab-server      1.2.0
Keras-Preprocessing    1.1.2
kiwisolver             1.2.0
lab                    6.0
lightgbm               3.0.0
Mako                   1.0.7
Markdown               3.3.1
MarkupSafe             0.23
matplotlib             3.3.1
mccabe                 0.6.1
mistune                0.8.4
mpmath                 1.1.0
multiprocess           0.70.10
murmurhash             1.0.2
mypy                   0.782
mypy-extensions        0.4.3
nbconvert              5.6.1
nbformat               5.0.7
nltk                   3.5
notebook               6.1.3
numpy                  1.18.5
oauthlib               3.1.0
opt-einsum             3.3.0
packaging              20.4
pandas                 1.1.2
pandocfilters          1.4.2
parso                  0.7.1
pathos                 0.2.6
pathspec               0.8.0
patsy                  0.5.1
pexpect                4.8.0
pickleshare            0.7.5
Pillow                 7.2.0
pip                    20.2.3
plac                   1.1.3
plotly                 4.9.0
pluggy                 0.13.1
pox                    0.2.8
ppft                   1.6.6.2
preshed                3.0.2
prometheus-client      0.8.0
prompt-toolkit         3.0.6
protobuf               3.13.0
ptyprocess             0.6.0
py                     1.9.0
pyasn1                 0.4.8
pyasn1-modules         0.2.8
pycodestyle            2.6.0
pycparser              2.20
pyflakes               2.2.0
pyglet                 1.5.0
Pygments               2.6.1
pyparsing              2.4.7
pyrsistent             0.16.0
pytest                 6.1.1
python-dateutil        2.8.1
pytz                   2020.1
pyzmq                  19.0.2
qtconsole              4.7.6
QtPy                   1.9.0
regex                  2020.7.14
requests               2.24.0
requests-oauthlib      1.3.0
retrying               1.3.3
rsa                    4.6
s3transfer             0.3.3
scikit-learn           0.23.2
scipy                  1.5.2
seaborn                0.10.1
Send2Trash             1.5.0
seqlearn               0.2
setuptools             36.5.0
simplejson             3.17.2
six                    1.15.0
sklearn-deap2          0.2.2
smart-open             2.1.0
spacy                  2.3.2
srsly                  1.0.2
statsmodels            0.11.1
sympy                  1.6.2
tabulate               0.8.7
tensorboard            2.3.0
tensorboard-plugin-wit 1.7.0
tensorflow             2.3.1
tensorflow-estimator   2.3.0
termcolor              1.1.0
terminado              0.8.3
testpath               0.4.4
thinc                  7.4.1
threadpoolctl          2.1.0
toml                   0.10.1
torch                  1.6.0
tornado                6.0.4
tqdm                   4.48.2
traitlets              4.3.3
txt2tags               3.7
typed-ast              1.4.1
typing-extensions      3.7.4.2
urllib3                1.25.10
vecstack               0.4.0
wasabi                 0.7.1
wcwidth                0.2.5
webencodings           0.5.1
Werkzeug               1.0.1
wheel                  0.35.1
widgetsnbextension     3.5.1
wrapt                  1.12.1
xgboost                1.2.0
```

**Comment by dylanpeifer** [comment] 2020-10-19 17:20
OK, it will likely be the end of the month before I get a good chance to look at this. I will update here if and when I fix or change the multiprocessing code. In the meantime, let me know if you have any problems with using `--parallel False`.

**Comment by dylanpeifer** [comment] 2021-04-28 01:54
As the latest release no longer uses any multiprocessing code, I'm closing this issue.

**Closed by dylanpeifer** 2021-04-28 01:54 UTC
